### ISSUE TITLE
Refactor stage.lua

### ISSUE THREAD

**Issue by garcia1000** [garcia1000/StrataGem#16]
Either:
Stage becomes a container for all the stuff, with stage:draw()

Or:
Move stuff from stage module into more appropriate things
Eventually it will just have width and height, probably stored in draw.lua
All movements/positioning will be passed as a percentage of width or height

**Comment by ProtonZero** [comment]
Grid was recently extracted from Stage, so Stage is currently just a read-only lookup table for various display metrics. It's not too bad leaving it as is, but the alternative is just chucking all of Stage's variables into Game.

**Comment by garcia1000** [comment]
Stage is fine now I think, meh
