### ISSUE TITLE
Update all graphical coordinates to use 1280×720 canvas.

### ISSUE THREAD

**Issue by ProtonZero** [garcia1000/StrataGem#32]
Currently a lot of things are setting their display parameters by multiplying the screen dimensions by certain percentages. These should all be changed to their equivalent values in 720p to significantly reduce the amount of things that reference Stage (to eventually refactor it #16).

**Comment by garcia1000** [comment]
Can we close this? We anticipate using multiple dimensions as mobile resolutions differ widely. The references to stage.width and stage.height make this easier to do.
